export const Questions=[
    {
        prompt:"What is React?",
        optionA:"A programming language",
        optionB:"A JavaScript framework",
        optionC:"A JavaScript library for building user interfaces",
        optionD:"A database management system",
        answer:"C",
    },
    {
        prompt:"Which of the following is true about React components?",
        optionA:"They are only used for styling",
        optionB:"They cannot hold any state",
        optionC:"They can be either functional or class-based",
        optionD:"They are only used for server-side rendering",
        answer:"C",
    },
    {
        prompt:"What is JSX in React?",
        optionA:" A templating language",
        optionB:" A styling framework",
        optionC:"A testing library",
        optionD:"A syntax extension for JavaScript",
        answer:"D",
    },
    {
        prompt:"What does the 'setState' method do in React?",
        optionA:"Updates the component's state",
        optionB:"Renders the component on the page",
        optionC:"Defines the component's initial state",
        optionD:"Adds a new property to the component",
        answer:"A",
    },
    {
        prompt:"What is the purpose of props in React?",
        optionA:"They are used for component styling",
        optionB:"They hold the component's state",
        optionC:"They are used for passing data between components",
        optionD:" They determine the component's lifecycle methods",
        answer:"C",
    },
    {
        prompt:"What is the virtual DOM in React?",
        optionA:"A DOM manipulation library",
        optionB:"The actual rendered DOM on the webpage",
        optionC:"A copy of the DOM used for efficient rendering",
        optionD:"A debugging tool for React components",
        answer:"C",
    },
    {
        prompt:"Which hook is used to manage state in functional components in React?",
        optionA:"useState",
        optionB:"useEffect",
        optionC:"useContext",
        optionD:"useReducer",
        answer:"A",
    },
    {
        prompt:"What is the purpose of the 'key' prop in React?",
        optionA:"It assigns a unique identifier to each component",
        optionB:"It defines the component's CSS styles",
        optionC:"It specifies the component's initial state",
        optionD:"It determines the component's lifecycle methods",
        answer:"A",
    },
    {
        prompt:"Which lifecycle method is invoked after a component has been rendered for the first time?",
        optionA:"componentDidMount",
        optionB:"componentWillUnmount",
        optionC:"componentDidUpdate",
        optionD:"shouldComponentUpdate",
        answer:"A",
    },
    {
        prompt:"What is the purpose of the 'render' method in React class components?",
        optionA:"It updates the component's state",
        optionB:"It returns the JSX representation of the component",
        optionC:"It defines the component's initial state",
        optionD:"It adds event listeners to the component",
        answer:"B",
    },
]